const std = @import("std");
const lexical = @import("lexer.zig");
const syntax = @import("parser.zig");

const Error = error{InvalidArguments};

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    var args = try init.minimal.args.iterateAllocator(gpa);
    defer args.deinit();
    _ = args.next();
    const input = args.next() orelse return usage();
    const output = args.next() orelse return usage();
    if (args.next() != null) return usage();

    const source = try std.Io.Dir.cwd().readFileAlloc(io, input, gpa, .limited(64 * 1024 * 1024));
    defer gpa.free(source);

    try validateSyntax(gpa, source, input);

    var generated = std.Io.Writer.Allocating.init(gpa);
    defer generated.deinit();
    try emitLauncher(source, input, &generated.writer);
    const c_source = try generated.toOwnedSlice();
    defer gpa.free(c_source);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = output, .data = c_source });
}

fn usage() Error {
    std.debug.print("usage: zlua-emit <input.lua> <output.c>\n", .{});
    return error.InvalidArguments;
}

fn validateSyntax(allocator: std.mem.Allocator, source: []const u8, source_name: []const u8) !void {
    // Run the lexer explicitly first so even a malformed first token gets a
    // precise diagnostic before parser construction.
    var lexer = lexical.Lexer.init(source);
    while (true) {
        const token_value = lexer.next() catch |err| {
            std.debug.print("{s}:{d}:{d}: lexical error: {s}\n", .{
                source_name, lexer.failure.line, lexer.failure.column, lexer.failure.message,
            });
            return err;
        };
        if (token_value.tag == .eof) break;
    }

    var parser = try syntax.Parser.init(allocator, source);
    defer parser.deinit();
    parser.parse() catch |err| {
        std.debug.print("{s}:{d}:{d}: syntax error: {s}\n", .{
            source_name, parser.failure.line, parser.failure.column, parser.failure.message,
        });
        return err;
    };
}

/// Emits a self-contained launcher containing the exact Lua source bytes. The
/// launcher resolves the LuaJIT 5.1 ABI dynamically, so generated programs use
/// complete Lua semantics and remain compatible with Lua C modules.
fn emitLauncher(source: []const u8, source_name: []const u8, out: *std.Io.Writer) !void {
    try out.writeAll(
        \\/* Generated by zlua-aot: LuaJIT 5.1 whole-program launcher. */
        \\#include <dlfcn.h>
        \\#include <stdio.h>
        \\#include <stdlib.h>
        \\#include <string.h>
        \\typedef struct lua_State lua_State;
        \\typedef lua_State *(*newstate_fn)(void);
        \\typedef void (*openlibs_fn)(lua_State *);
        \\typedef int (*loadbuffer_fn)(lua_State *, const char *, size_t, const char *);
        \\typedef int (*pcall_fn)(lua_State *, int, int, int);
        \\typedef const char *(*tolstring_fn)(lua_State *, int, size_t *);
        \\typedef void (*close_fn)(lua_State *);
        \\typedef void (*pushstring_fn)(lua_State *, const char *);
        \\typedef void (*rawseti_fn)(lua_State *, int, int);
        \\typedef void (*createtable_fn)(lua_State *, int, int);
        \\typedef void (*setglobal_fn)(lua_State *, int, const char *);
        \\static const unsigned char program[] = {
        \\
    );
    for (source, 0..) |byte, i| {
        if (i % 16 == 0) try out.writeAll("  ");
        try out.print("0x{x:0>2},", .{byte});
        if (i % 16 == 15) try out.writeAll("\n") else try out.writeAll(" ");
    }
    try out.writeAll("\n};\nstatic const size_t program_len = sizeof(program);\n");
    try out.writeAll("static const char chunk_name[] = \"");
    try writeCString(source_name, out);
    try out.writeAll(
        \\";
        \\static void *symbol(void *h, const char *name) {
        \\  void *p = dlsym(h, name);
        \\  if (!p) { fprintf(stderr, "zlua-aot: missing LuaJIT symbol %s: %s\n", name, dlerror()); exit(127); }
        \\  return p;
        \\}
        \\int main(int argc, char **argv) {
        \\  const char *libs[] = { "libluajit-5.1.so.2", "libluajit-5.1.so", "libluajit.so", NULL };
        \\  void *h = NULL;
        \\  for (int i = 0; libs[i] && !h; ++i) h = dlopen(libs[i], RTLD_NOW | RTLD_GLOBAL);
        \\  if (!h) { fprintf(stderr, "zlua-aot: LuaJIT 2.x runtime not found: %s\n", dlerror()); return 127; }
        \\  newstate_fn newstate = (newstate_fn)symbol(h, "luaL_newstate");
        \\  openlibs_fn openlibs = (openlibs_fn)symbol(h, "luaL_openlibs");
        \\  loadbuffer_fn loadbuffer = (loadbuffer_fn)symbol(h, "luaL_loadbuffer");
        \\  pcall_fn pcall_ = (pcall_fn)symbol(h, "lua_pcall");
        \\  tolstring_fn tolstring = (tolstring_fn)symbol(h, "lua_tolstring");
        \\  close_fn close_ = (close_fn)symbol(h, "lua_close");
        \\  pushstring_fn pushstring = (pushstring_fn)symbol(h, "lua_pushstring");
        \\  rawseti_fn rawseti = (rawseti_fn)symbol(h, "lua_rawseti");
        \\  createtable_fn createtable = (createtable_fn)symbol(h, "lua_createtable");
        \\  setglobal_fn setglobal = (setglobal_fn)symbol(h, "lua_setfield");
        \\  lua_State *L = newstate();
        \\  if (!L) { fputs("zlua-aot: cannot create Lua state\n", stderr); return 1; }
        \\  openlibs(L);
        \\  createtable(L, argc, 0);
        \\  for (int i = 0; i < argc; ++i) { pushstring(L, argv[i]); rawseti(L, -2, i); }
        \\  /* LUA_GLOBALSINDEX is -10002 in the Lua 5.1 ABI. */
        \\  setglobal(L, -10002, "arg");
        \\  int status = loadbuffer(L, (const char *)program, program_len, chunk_name);
        \\  if (!status) status = pcall_(L, 0, -1, 0);
        \\  if (status) {
        \\    const char *message = tolstring(L, -1, NULL);
        \\    fprintf(stderr, "%s\n", message ? message : "unknown LuaJIT error");
        \\  }
        \\  close_(L); dlclose(h); return status ? 1 : 0;
        \\}
        \\
    );
}

fn writeCString(value: []const u8, out: *std.Io.Writer) !void {
    for (value) |byte| {
        if (byte == '\\')
            try out.writeAll("\\\\")
        else if (byte == '"')
            try out.writeAll("\\\"")
        else if (byte >= 0x20 and byte <= 0x7e)
            try out.writeByte(byte)
        else
            try out.print("\\x{x:0>2}", .{byte});
    }
}
