const std = @import("std");
const lexical = @import("lexer.zig");
const syntax = @import("parser.zig");
const numeric = @import("numeric.zig");
const hybrid = @import("hybrid.zig");

const Error = error{InvalidArguments};

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    var args = try init.minimal.args.iterateAllocator(gpa);
    defer args.deinit();
    _ = args.next();
    const input = args.next() orelse return usage();
    const output = args.next() orelse return usage();
    if (args.next() != null) return usage();

    const source = try std.Io.Dir.cwd().readFileAlloc(io, input, gpa, .limited(64 * 1024 * 1024));
    defer gpa.free(source);

    try validateSyntax(gpa, source, input);

    var generated = std.Io.Writer.Allocating.init(gpa);
    defer generated.deinit();
    const native = try numeric.emitIfEligible(gpa, source, &generated.writer);
    var plan: hybrid.Plan = undefined;
    var mixed = false;
    if (!native) {
        plan = hybrid.analyze(gpa, source) catch |err| {
            std.debug.print("{s}: AOT eligibility error: annotated function is outside the supported numeric subset\n", .{input});
            return err;
        };
        defer plan.deinit();
        mixed = plan.kernels.items.len != 0;
        try emitLauncher(if (mixed) plan.transformed else source, input, if (mixed) &plan else null, &generated.writer);
    }
    std.debug.print("zlua-aot backend: {s}\n", .{if (native) "native-numeric" else if (mixed) "hybrid-functions" else "luajit-fallback"});
    const c_source = try generated.toOwnedSlice();
    defer gpa.free(c_source);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = output, .data = c_source });
}

fn usage() Error {
    std.debug.print("usage: zlua-emit <input.lua> <output.c>\n", .{});
    return error.InvalidArguments;
}

fn validateSyntax(allocator: std.mem.Allocator, source: []const u8, source_name: []const u8) !void {
    // Run the lexer explicitly first so even a malformed first token gets a
    // precise diagnostic before parser construction.
    var lexer = lexical.Lexer.init(source);
    while (true) {
        const token_value = lexer.next() catch |err| {
            std.debug.print("{s}:{d}:{d}: lexical error: {s}\n", .{
                source_name, lexer.failure.line, lexer.failure.column, lexer.failure.message,
            });
            return err;
        };
        if (token_value.tag == .eof) break;
    }

    var parser = try syntax.Parser.init(allocator, source);
    defer parser.deinit();
    parser.parse() catch |err| {
        std.debug.print("{s}:{d}:{d}: syntax error: {s}\n", .{
            source_name, parser.failure.line, parser.failure.column, parser.failure.message,
        });
        return err;
    };
}

/// Emits a self-contained launcher containing the exact Lua source bytes. The
/// launcher resolves the LuaJIT 5.1 ABI dynamically, so generated programs use
/// complete Lua semantics and remain compatible with Lua C modules.
fn emitLauncher(source: []const u8, source_name: []const u8, plan: ?*const hybrid.Plan, out: *std.Io.Writer) !void {
    try out.writeAll(
        \\/* Generated by zlua-aot: LuaJIT 5.1 whole-program launcher. */
        \\#include <dlfcn.h>
        \\#include <stdio.h>
        \\#include <stdlib.h>
        \\#include <string.h>
        \\typedef struct lua_State lua_State;
        \\typedef lua_State *(*newstate_fn)(void);
        \\typedef void (*openlibs_fn)(lua_State *);
        \\typedef int (*loadbuffer_fn)(lua_State *, const char *, size_t, const char *);
        \\typedef int (*pcall_fn)(lua_State *, int, int, int);
        \\typedef const char *(*tolstring_fn)(lua_State *, int, size_t *);
        \\typedef void (*close_fn)(lua_State *);
        \\typedef void (*pushstring_fn)(lua_State *, const char *);
        \\typedef void (*rawseti_fn)(lua_State *, int, int);
        \\typedef void (*createtable_fn)(lua_State *, int, int);
        \\typedef void (*setglobal_fn)(lua_State *, int, const char *);
        \\typedef int (*lua_CFunction)(lua_State *);
        \\typedef int (*gettop_fn)(lua_State *);
        \\typedef int (*type_fn)(lua_State *, int);
        \\typedef double (*tonumber_fn)(lua_State *, int);
        \\typedef void (*pushnumber_fn)(lua_State *, double);
        \\typedef void (*pushcclosure_fn)(lua_State *, lua_CFunction, int);
        \\typedef void (*getfield_fn)(lua_State *, int, const char *);
        \\typedef void (*insert_fn)(lua_State *, int);
        \\typedef int (*error_fn)(lua_State *);
        \\static gettop_fn z_gettop; static type_fn z_type; static tonumber_fn z_tonumber;
        \\static pushnumber_fn z_pushnumber; static getfield_fn z_getfield;
        \\static insert_fn z_insert; static pcall_fn z_pcall; static error_fn z_error;
        \\static const unsigned char program[] = {
        \\
    );
    for (source, 0..) |byte, i| {
        if (i % 16 == 0) try out.writeAll("  ");
        try out.print("0x{x:0>2},", .{byte});
        if (i % 16 == 15) try out.writeAll("\n") else try out.writeAll(" ");
    }
    try out.writeAll("\n};\nstatic const size_t program_len = sizeof(program);\n");
    if (plan) |mixed| for (mixed.kernels.items, 0..) |*kernel, i| {
        try out.print("static double zlua_impl_{d}(", .{i});
        for (kernel.params.items, 0..) |_, p| {
            if (p != 0) try out.writeAll(", ");
            try out.print("double p{d}", .{p});
        }
        try out.writeAll(") { return ");
        try hybrid.emitExpr(mixed, kernel, kernel.result, out);
        try out.writeAll("; }\n");
        try out.print("static int zlua_wrap_{d}(lua_State *L) {{\n  int n = z_gettop(L);\n  if (n == {d}", .{ i, kernel.params.items.len });
        for (kernel.params.items, 0..) |_, p| try out.print(" && z_type(L, {d}) == 3", .{p + 1});
        try out.writeAll(") {\n    z_pushnumber(L, zlua_impl_");
        try out.print("{d}(", .{i});
        for (kernel.params.items, 0..) |_, p| {
            if (p != 0) try out.writeAll(", ");
            try out.print("z_tonumber(L, {d})", .{p + 1});
        }
        try out.writeAll(")); return 1;\n  }\n  z_getfield(L, -10002, \"__zlua_fallback_");
        try out.print("{d}\");\n  z_insert(L, 1);\n  if (z_pcall(L, n, -1, 0)) return z_error(L);\n  return z_gettop(L);\n}}\n", .{i});
    };
    try out.writeAll("static const char chunk_name[] = \"");
    try writeCString(source_name, out);
    try out.writeAll(
        \\";
        \\static void *symbol(void *h, const char *name) {
        \\  void *p = dlsym(h, name);
        \\  if (!p) { fprintf(stderr, "zlua-aot: missing LuaJIT symbol %s: %s\n", name, dlerror()); exit(127); }
        \\  return p;
        \\}
        \\int main(int argc, char **argv) {
        \\  const char *libs[] = { "libluajit-5.1.so.2", "libluajit-5.1.so", "libluajit.so", NULL };
        \\  void *h = NULL;
        \\  for (int i = 0; libs[i] && !h; ++i) h = dlopen(libs[i], RTLD_NOW | RTLD_GLOBAL);
        \\  if (!h) { fprintf(stderr, "zlua-aot: LuaJIT 2.x runtime not found: %s\n", dlerror()); return 127; }
        \\  newstate_fn newstate = (newstate_fn)symbol(h, "luaL_newstate");
        \\  openlibs_fn openlibs = (openlibs_fn)symbol(h, "luaL_openlibs");
        \\  loadbuffer_fn loadbuffer = (loadbuffer_fn)symbol(h, "luaL_loadbuffer");
        \\  pcall_fn pcall_ = (pcall_fn)symbol(h, "lua_pcall");
        \\  tolstring_fn tolstring = (tolstring_fn)symbol(h, "lua_tolstring");
        \\  close_fn close_ = (close_fn)symbol(h, "lua_close");
        \\  pushstring_fn pushstring = (pushstring_fn)symbol(h, "lua_pushstring");
        \\  rawseti_fn rawseti = (rawseti_fn)symbol(h, "lua_rawseti");
        \\  createtable_fn createtable = (createtable_fn)symbol(h, "lua_createtable");
        \\  setglobal_fn setglobal = (setglobal_fn)symbol(h, "lua_setfield");
        \\  pushcclosure_fn pushcclosure = (pushcclosure_fn)symbol(h, "lua_pushcclosure");
        \\  z_gettop = (gettop_fn)symbol(h, "lua_gettop");
        \\  z_type = (type_fn)symbol(h, "lua_type");
        \\  z_tonumber = (tonumber_fn)symbol(h, "lua_tonumber");
        \\  z_pushnumber = (pushnumber_fn)symbol(h, "lua_pushnumber");
        \\  z_getfield = (getfield_fn)symbol(h, "lua_getfield");
        \\  z_insert = (insert_fn)symbol(h, "lua_insert");
        \\  z_error = (error_fn)symbol(h, "lua_error");
        \\  z_pcall = pcall_;
        \\  lua_State *L = newstate();
        \\  if (!L) { fputs("zlua-aot: cannot create Lua state\n", stderr); return 1; }
        \\  openlibs(L);
        \\  createtable(L, argc, 0);
        \\  for (int i = 0; i < argc; ++i) { pushstring(L, argv[i]); rawseti(L, -2, i); }
        \\  /* LUA_GLOBALSINDEX is -10002 in the Lua 5.1 ABI. */
        \\  setglobal(L, -10002, "arg");
        \\
    );
    if (plan) |mixed| for (mixed.kernels.items, 0..) |*kernel, i| {
        try out.print("  pushcclosure(L, zlua_wrap_{d}, 0); setglobal(L, -10002, \"", .{i});
        try writeCString(kernel.name.text(mixed.source), out);
        try out.writeAll("\");\n");
    };
    try out.writeAll(
        \\  int status = loadbuffer(L, (const char *)program, program_len, chunk_name);
        \\  if (!status) status = pcall_(L, 0, -1, 0);
        \\  if (status) {
        \\    const char *message = tolstring(L, -1, NULL);
        \\    fprintf(stderr, "%s\n", message ? message : "unknown LuaJIT error");
        \\  }
        \\  close_(L); dlclose(h); return status ? 1 : 0;
        \\}
        \\
    );
}

fn writeCString(value: []const u8, out: *std.Io.Writer) !void {
    for (value) |byte| {
        if (byte == '\\')
            try out.writeAll("\\\\")
        else if (byte == '"')
            try out.writeAll("\\\"")
        else if (byte >= 0x20 and byte <= 0x7e)
            try out.writeByte(byte)
        else
            try out.print("\\x{x:0>2}", .{byte});
    }
}
